apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-node
spec:
  selector:
    matchLabels:
      app: hello-world-node
  template:
    metadata:
      labels:
        app: hello-world-node
    spec:
      containers:
      - image: okteto/node-getting-started:hello-world
        name: hello-world-node

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-node
spec:
  type: ClusterIP
  ports:
  - name: "hello-world-node"
    port: 3000
  selector:
    app: hello-world-node

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-node
  annotations:
    dev.okteto.com/generate-host: hello-world-node
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: hello-world-node
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
